### PR TITLE
Pipe source to clang instead of forcing the write

### PR DESCRIPTION
**Pull request by mlen**
Previously the file was written to be able to trigger clang with the latest version of the buffer for completion. This patch passes the input as the second argument to system function.

This patch lacks nvim support, however I don't use it and I wasn't able to find how to pass a string as stdin in the documentation and in the source code. I will happily add nvim support to this patch.

### CODE REVIEW

**Comment by justmao945** [comment]
Hi @mlen , this patch is really really very great! Thank you very much. As someone have asked me, why need to write file before completion? I must to tell them, I don't know how to complete code without writing file to disk. :sob: 

> This patch lacks nvim support, however I don't use it and I wasn't able to find how to pass a string as stdin in the documentation and in the source code. I will happily add nvim support to this patch.

Do you mean can't find the documentation in nvim ? Seems another patch provided by @syswow did some work in nvim, I still need to review code in this big patch.

Hi @syswow , can you explain your work to solve this problem in nvim ?

**Comment by mlen** [comment]
I even grepped the source code for `fstderr`, `fstdout` to check if something like `fstdin` is available, but I didn't find anything.

There's one more thing I discovered, but I think it's a minor one: when errors popup opens, it says `<stdin>` instead of the filename, but for me it's a minor issue. And it can be easily fixed by replacing every occurrence of `<stdin>:` with the filename of the current buffer.

**Comment by justmao945** [comment]
OK, seems we can fire a feature request issue to support `fstdin` in nvim :smile: 
Yes, may feel better to replace the weird `<stdin>`.

**Comment by justmao945** [comment]
Hi @mlen , I forgot some important thing that this patch breaks nvim, but I still merged it. So if you have any update to support it is OK.

**Comment by syswow** [comment]
@mlen  @justmao945  I will try to implement pipe stdin to nvim.

**Pull request merged**
