### PR TITLE
We only need to parse include dirs and defines from compile databse

### PR DESCRIPTION
**Pull request by c0r73x**
Hi

I noticed that the compile database contains flags that should not needed for completion. I changed it to only fetch defines and include directories.

### CODE REVIEW

**Comment by justmao945** [comment]
OK. Can you paste here about ignored flags ?

**Comment by c0r73x** [comment]
Sure, the compile_commands.json can contain warning flags and debug flags that shouldnt be needed for completion. for example "-O2 -Wall" and such.

I rewrote it to only search for -I and -D, defines might not be needed but some code can classes that are only visible with certain defines.

**Comment by c0r73x** [comment]
I could add a new option where users can specify what flags they want to include in b:clang_options for flexability.

For example something like g:clang_compilation_flags = "ID" where users can add the O and W if they for some reason want them :P

**Comment by justmao945** [comment]
Is it necessary to remove unused flags in completion ? Can you explain it ?

**Comment by c0r73x** [comment]
Might not be necessary, but it's cleaner to see if something goes wrong when echoing . Also i'm unsure if some compiler flags might accually break completion. 

The old code just takes everything between the compiler binary and the -o flag. the new code should be alot safer since it parses the string for the flags you need. So it's just a fix to prevent things from blowing up :)

**Comment by justmao945** [comment]
Got it. We just preserve `-DI` in this version, and can add more flags if is necessary in future :smiley:

**Pull request merged**
